env: fix inconsistent `dot_exe`, fix #249
vlang/vab pull request #254
Opened 2023-01-18 07:09 UTC by km19809

This PR fixes #249.
Also, it makes usages of `dot_exe` consistent.

`dot_exe` was used in several functions but was defined separately.
By making it module-level constant, we can reuse it without re-defining.

2023-01-18 20:40 UTC, Larpon requested changes
I like the solution - just need the the `dot_exe` on `os.exists_in_system_path` use and `os.find_abs_path_of_executable`.

2023-01-18 20:40 UTC, Larpon commented on android/env/env.v
>  		if os.exists_in_system_path('adb') {
We should add the `dot_exe` here as well since `os.exists_in_system_path` uses `os.find_abs_path_of_executable` which uses `os.is_executable` under the hood.

2023-01-18 20:40 UTC, Larpon commented on android/env/env.v
>  		if os.exists_in_system_path('adb') {
The same goes for `os.find_path_of_executable` just below

2023-01-19 07:11 UTC, km19809 commented on android/env/env.v
>  		if os.exists_in_system_path('adb') {
No, `os.find_abs_path_of_executable` is slightly different.
Please check this [line](https://github.com/vlang/v/blob/d850d3caba88fe2f7cc3f10934751dabb2015053/vlib/os/os.v#L473).
```v
for suffix in executable_suffixes {
	fexepath := exepath + suffix
```
The variable `fexepath` is joined into `found_abs_path`
```v
			found_abs_path := join_path_single(p, fexepath)
			$if trace_find_abs_path_of_executable ? {
				dump(found_abs_path)
			}
			if exists(found_abs_path) && is_executable(found_abs_path) {
				res = found_abs_path
				break
			}
```

executable_suffixes is defined in `os_<os>.c.v`.
In [`os_windows.c.v`](https://github.com/vlang/v/blob/e419faf7464e3a6217c139ebfa3b432e0bbef001/vlib/os/os_windows.c.v#L17):
```v
const executable_suffixes = ['.exe', '.bat', '.cmd', '']
```

So, if I add `dot_exe` to '.exe', it would be unnecessary.

2023-01-19 12:16 UTC, JalonSolov commented on android/env/env.v
>  		if os.exists_in_system_path('adb') {
Actually... that const isn't correct, if you really want this to work like Windows.  It should read the `PATHEXT` env var at runtime, and use the values from there.  Yes, this means you could get different valuess on different Windows systems, but... that's Windows.

2023-01-19 14:01 UTC, JalonSolov commented on android/env/env.v
>  		if os.exists_in_system_path('adb') {
Yes, because Windows is the only OS that decides something is executable by extension.  All the others do it by checking the `execute` bit on the file info.

2023-01-30 09:30 UTC, Larpon commented on android/env/env.v
>  		if os.exists_in_system_path('adb') {
@km19809 you are right, that's a bit messy - sorry for the delay on this.

2023-01-30 09:31 UTC, Larpon approved these changes

2023-01-30 09:31 UTC, merged