opt.output: default file name (for apk or aab) is now name of the work dir
vlang/vab pull request #277
Opened 2023-12-28 13:03 UTC by scriptmaster

What this PR does and why
---
When issuing `vab .` or `vab run .` the default file name produced is based on a hard-coded string (V Test App). This PR changes the default file name produced to the work dir (similar to what v compiler does).

Why
---
The default .apk or .aac file name is not matching with the expectation of how a `v .` does, hence this PR.

2023-12-30 10:36 UTC, Larpon requested changes

2023-12-30 10:36 UTC, Larpon commented on cli/options.v
> +			default_file_name = os.getwd().all_after_last('/').replace(os.path_separator.str(), '').replace(' ',
The name should be resolved from `opt.input` not `os.getwd()` as `vab` can be run from anywhere:
See this example where I've built `vab` from this PR on my machine:
![image](https://github.com/vlang/vab/assets/768942/b6ff2f68-065a-434a-b815-e3fb054bc6ab)

In this case the output should have been resolved to `bezier.apk` but it produced instead `vab.apk`

2023-12-30 10:36 UTC, Larpon commented on examples/bezier/app.v
Please remove this example, it is already in the V main repository.
Our goal is to have as many as V's examples compatible with `vab` as possible and since V is one of `vab`'s dependencies already it avoids (a lot of) code duplication that needs to be maintained in two places.

Users can use V's `gg` examples for testing

2023-12-30 10:36 UTC, Larpon commented on cli/options.v
The whole file needs formatting via `v fmt`

2024-09-11 12:40 UTC, larpon commented
Re-open and fix if this is still active

2024-09-11 12:40 UTC, closed without merging